title: Altonhill House test
description: Welcome to Altonhill House
google_analytics:
github: 
  is_project_page: false
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
